--CREATE TABLE publi.users (
--    id_user varchar(36) NOT NULL,
--    first_name varchar(255) NOT NULL,
--    last_name varchar(255) NOT NULL,
--    username varchar(255) NOT NULL,
--    "password" varchar(255) NOT NULL,
--    "role" varchar(255) NOT NULL
--);